name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: galiseregin/sample-app:latest

    - name: Deploy to server
      run: |
        ssh -i /path/to/your/ssh_key ec2-user@your-server-ip 'cd /home/centos/app && docker-compose up -d'
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

